### ISSUE TITLE
[BUG] allspeakbeta install and missing menu links

### ISSUE THREAD

**Issue by Tom-Neverwinter** [SillyTavern/SillyTavern-Launcher#90]
### Environment

🪟 Windows

### System

windows 10

### Describe the problem

when you go to load alltalk as a menu item it fails to launch as it appears it still coded to load the old v1 not v2

espeak is not installed [may have to do with the "this is not compatible" with windows warning]

[AllTalk TTS]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk TTS]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk TTS]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk TTS]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk TTS] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk TTS]
[AllTalk TTS] Start-up Mode     : Standalone mode
[AllTalk ] WAV file deletion    :
[AllTalk TTS] Github updated    : 12th December 2024 at 06:28 Branch: alltalkbeta
[AllTalk ENG] Transcoding       : ffmpeg found
[AllTalk ENG] DeepSpeed version : 0.14.0+ce78a63
[AllTalk ENG] Python Version    : 3.11.11
[AllTalk ENG] PyTorch Version   : 2.2.1
[AllTalk ENG] CUDA Version      : 12.1
[AllTalk ENG]
[AllTalk ENG] Warning: Model folder 'tts_models--en--jenny--jenny' missing config.json
[AllTalk ENG] Model/Engine : tts_models--en--vctk--vits loading into cuda
[AllTalk TTS] Error Error during setup: [!] No espeak backend found. Install espeak-ng or espeak to your system.. Continuing without the TTS model.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@Tom-Neverwinter I fixed the download bug can you start the launcher and try to install alltalk v2 again? uninstall first from launcher then install again

**Comment by Tom-Neverwinter** [comment]
reset the custom launcher option and sadly it still fails to find alltalk

```
   Choose Your Destiny (default is 1): 4
Executing custom shortcut...
Launching SillyTavern...
[14:20:29.41] [INFO] SillyTavern launched in a new window.
Launching  AllTalk :...
Now executing: call :start_alltalk
The system cannot find the batch label specified - start_alltalk
 AllTalk : Launched in a new window.
[14:20:29.42] [INFO] Custom shortcut executed.
Press any key to continue . . .
```
manually loading and running a few tests

everything in alltalk appears to work :)

amazing work!!!

**Comment by deffcolony** [comment]
@Tom-Neverwinter Ohh right... yeah i will add the alltalk V2 to the custom launcher. you can currently launch it from: 
`/ Home / Toolbox / App Launcher / Voice Generation / AllTalk`

**Comment by Tom-Neverwinter** [comment]
I found another one. using I beleive the sovit engine it never loads the webui or outputs the webui address. 

it also complains about espeak

```
[AllTalk TTS]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk TTS]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk TTS]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk TTS]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk TTS] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk TTS]
[AllTalk TTS] Start-up Mode     : Standalone mode
[AllTalk ] WAV file deletion    :
[AllTalk TTS] Github updated    : 23rd December 2024 at 06:50 Branch: alltalkbeta
[AllTalk ENG] Transcoding       : ffmpeg found
[AllTalk ENG] DeepSpeed version : 0.14.0+ce78a63
[AllTalk ENG] Python Version    : 3.11.11
[AllTalk ENG] PyTorch Version   : 2.2.1
[AllTalk ENG] CUDA Version      : 12.1
[AllTalk ENG]
[AllTalk ENG] Warning: Model folder 'tts_models--en--jenny--jenny' missing config.json
[AllTalk ENG] Model/Engine : tts_models--en--vctk--vits loading into cuda
[AllTalk TTS] Error Error during setup: [!] No espeak backend found. Install espeak-ng or espeak to your system.. Continuing without the TTS model.
[AllTalk TTS] Warning TTS Engine has NOT started up yet. Will keep trying for 240 seconds maximum. Please wait.
[AllTalk GEN] Warning The selected TTS Engine does not support streaming. To use streaming, please select a TTS
[AllTalk TTS] Warning Mechanical hard drives and a slow PCI BUS are examples of things that can affect load times.
[AllTalk GEN] Warning Engine that has streaming capability. You can find the streaming support information for
[AllTalk TTS] Warning Some TTS engines index their AI TTS models on loading, which can be slow on CPU or old systems.
[AllTalk GEN] Warning each TTS Engine in its 'Engine Information' section of the Gradio interface.
[AllTalk TTS] Warning Using one of the other TTS engines on slower systems can help ease this issue.
[AllTalk TTS] Starting streaming TTS generation for: tell me a joke
[AllTalk GEN] Warning The selected TTS Engine does not support streaming. To use streaming, please select a TTS
[AllTalk GEN] Warning Engine that has streaming capability. You can find the streaming support information for
[AllTalk GEN] Warning each TTS Engine in the 'Engine Information' section of the Gradio interface.
[AllTalk GEN] Error Value error occurred: Streaming not supported by current TTS engine
```

**Comment by Tom-Neverwinter** [comment]
might be the enviroment variable isnt set? https://huggingface.co/hexgrad/Kokoro-82M/discussions/12#67742594fdeebf74f001ecfc 

I will have to find time to test this later.
